apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataops-app
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prod.dataops.local
      secretName: dataops-tls
  rules:
    - host: prod.dataops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dataops-app
                port:
                  number: 80
