apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataops-app
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - staging.dataops.local
      secretName: dataops-tls
  rules:
    - host: staging.dataops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dataops-app
                port:
                  number: 80
